/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          paper: '#ffffff',
          sand: '#121212',
          mist: '#1a1a1a',
          ink: '#ffffff',
          midnight: '#050505',
          navy: '#0a0a0a',
          gold: '#d4af37',
          'gold-deep': '#b89428',
          'gold-bright': '#d4af37',
          bronze: '#d4af37',
          copper: '#d4af37',
        },
        primary: {
          50: '#ffffff',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4af37',
          400: '#d4af37',
          500: '#d4af37',
          600: '#b89428',
          700: '#997a1e',
          800: '#1a1a1a',
          900: '#0a0a0a',
        },
        gold: {
          50: '#fdfaf3',
          100: '#f5ebd4',
          200: '#e8d48b',
          300: '#d4af37',
          400: '#d4af37',
          500: '#d4af37',
          600: '#b89428',
          700: '#997a1e',
          800: '#1a1a1a',
          900: '#0a0a0a',
        },
        neon: {
          gold: '#d4af37',
          'gold-deep': '#b89428',
          'gold-champagne': '#d4af37',
          'gold-light': '#d4af37',
          'gold-shine': '#d4af37',
          'gold-dark': '#b89428',
          cream: '#ffffff',
          amber: '#d4af37',
          blue: '#0a0a0a',
          'blue-light': '#1a1a1a',
          'blue-dark': '#050505',
        },
        dark: {
          50: '#ffffff',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#a3a3a3',
          400: '#737373',
          500: '#525252',
          600: '#262626',
          700: '#171717',
          800: '#121212',
          900: '#0a0a0a',
          950: '#000000',
        },
        black: '#000000',
        success: '#d4af37',
        warning: '#d4af37',
        danger: '#d4af37',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          'var(--font-roboto)',
          'Roboto',
          '"Segoe UI"',
          'system-ui',
          'sans-serif',
        ],
        display: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          'var(--font-roboto)',
          'Roboto',
          '"Segoe UI"',
          'system-ui',
          'sans-serif',
        ],
        spectral: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          'var(--font-roboto)',
          'Roboto',
          '"Segoe UI"',
          'system-ui',
          'sans-serif',
        ],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        glow: 'glow 2s ease-in-out infinite alternate',
        float: 'float 6s ease-in-out infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        glow: {
          '0%': { boxShadow: '0 0 12px rgba(212,175,55,0.2)' },
          '100%': { boxShadow: '0 0 24px rgba(212,175,55,0.4)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
      },
      backgroundImage: {},
    },
  },
  plugins: [],
}
